### ISSUE TITLE
Labeled containers do not show up in dashboard

### ISSUE THREAD

**Issue by andlil** [plugsy/core#12]
Hello!

Interesting project but I can't get it to work.

This is my docker-compose.yml

```
version: '3.3'
services:
  plugsy:
    image: plugsy/core
    container_name: plugsy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - './config:/config'
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.plugsy.loadbalancer.server.port=3000
      - traefik.http.routers.plugsy.entrypoints=websecure
      - traefik.http.routers.plugsy.rule=Host(`plugsy.domain.tld`)
      - traefik.http.routers.plugsy.tls=true
      - traefik.http.routers.plugsy.middlewares=security-headers@file
      - dockerDash.name=Plugsy
      - dockerDash.link=https://plugsy.domain.tld
    networks:
      - web
networks:
  web:
    external: true

```
Plugsy runs but only displays this
![Skärmavbild 2021-06-27 kl  11 27 47](https://user-images.githubusercontent.com/10003475/123539594-cbab2c80-d73a-11eb-9b7c-641295cd4243.png)

Shouldn't it pick up the labels on its own container and display them?
