### ISSUE TITLE
Minified React error

### ISSUE THREAD

**Issue by danielfomin96** [plugsy/core#15]
Hello,
Nice project! I am trying to set up the dashboard using docker-compose but I get the following error:
```
plugsy    | Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
plugsy    |     at a.b.render (/home/node/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:45:32)
plugsy    |     at a.b.read (/home/node/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
plugsy    |     at exports.renderToString (/home/node/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
plugsy    |     at renderPage (/home/node/node_modules/next/dist/next-server/server/render.js:54:854)
plugsy    |     at Object.ctx.renderPage (/home/node/app/.next/server/pages/_document.js:85:30)
plugsy    |     at Function.getInitialProps (/home/node/app/.next/server/chunks/590.js:542:19)
plugsy    |     at Function.getInitialProps (/home/node/app/.next/server/pages/_document.js:89:85)
plugsy    |     at loadGetInitialProps (/home/node/node_modules/next/dist/next-server/lib/utils.js:5:101)
plugsy    |     at renderToHTML (/home/node/node_modules/next/dist/next-server/server/render.js:54:1145)
plugsy    |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
This is my docker-compose.yml:
```
version: "2.1"
services:
  plugsy:
    image: plugsy/core
    container_name: plugsy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    restart: unless-stopped
```
Did I set it up wrong or is there a bug somewhere?
