### ISSUE TITLE
Possibility to add group ?

### ISSUE THREAD

**Issue by mattthhdp** [plugsy/core#38]
So it will be easier to "regroup" services
like website
      - Web a
      - Web b
 Game Server
      - Minecraft public
      - Minecraft creative
  Core services
      - Home Assistant
      - Traefik
      - Mosquitto
      - Plugsy
etc etc

**Comment by Inlustra** [comment]
I'm a little confused, if you look at the video in the README you should see that grouping is possible using the category label/config

**Comment by mattthhdp** [comment]
sorry i was in a hurry and see that it miss a lot of my original question (which was in my head ... why can you read inside people head !! ^^)
Is it possible to have 2 dockerDash.name, category, and link
so i can group lan and wan differently on my dashboard.

**Comment by Inlustra** [comment]
Sorry, I'm still not understanding the question, you can have one dockerDash.name etc per container.

Are you asking if you can have multiple for the same container? It put the same container in multiple categories?

**Comment by mattthhdp** [comment]
Im really sorry for the bad explaination
is it possible to have  2 dockerDash.link and group for the same container ? so i can put it on 2 group (lan and wan)
lets said something like this
  deluge:
    image: linuxserver/deluge ##V2
    container_name: deluge
    ports:
      - 8112:8112
      - 58846:58846
      ........
    labels:
      - "traefik.enable=true"
      - "dockerDash.name=Deluge"
      - "dockerDash.category=Media-LAN"
      - "dockerDash.category=Media-WAN"
      #- "dockerDash.icon=@styled-icons/fluentui-system-regular/Communication"
      - "dockerDash.link=http://Lanip:8112"
      - "dockerDash.link=https://wanip"

**Comment by Inlustra** [comment]
Unfortunately it's not really made to do that, what you're suggesting kind of feels to me like you should think about using the parents/children concept, it can have multiple:

```yml
      dockerDash.parents: 'transmission,jackett,prowlarr'
```

If you really do want to have multiple of the same, at the cost of more docker polling, you can use the config file

```json
{
  "$schema": "https://github.com/plugsy/core/releases/download/v3.0.1/config-schema.json",
  "connectors": [
    {
      "type": "DOCKER",
      "config": {}
    },
    {
      "type": "DOCKER",
      "config": {
        "labelConfig": {
          "categoryLabel": "dockerDash.category2",
          "iconLabel": "dockerDash.icon2",
          "linkLabel": "dockerDash.link2",
          "nameLabel": "dockerDash.name2",
          "parentsLabel": "dockerDash.parents2"
        }
      }
    }
  ]
}

```

And with this, you can now do what you're asking in your yaml
```yml
  deluge:
    image: linuxserver/deluge ##V2
    container_name: deluge
    ports:
      - 8112:8112
      - 58846:58846
      ........
    labels:
      - "traefik.enable=true"
      - "dockerDash.name=Deluge"
      - "dockerDash.category=Media-LAN"
      - "dockerDash.category2=Media-WAN"
      #- "dockerDash.icon=@styled-icons/fluentui-system-regular/Communication"
      - "dockerDash.link=http://Lanip:8112"
      - "dockerDash.link2=https://wanip"
```
